### ISSUE TITLE
What attributed to the better performance of the model compared to your earlier model?

### ISSUE THREAD

**Issue by xiankgx** [TachibanaYoshino/AnimeGANv2#7]
Hi, thanks for sharing your work. What in your opinion was the key to achieving better performance compared to your earlier model (v1) and/or other models?

I've roughly seen the code of this repo but I can't figure it out.

**Comment by TachibanaYoshino** [comment]
Hello, thank you for your attention. I will open source all the code in the near future. And once again released a lite version of AnimeGANv2, in order to be compatible with the efficiency of the mobile terminal, deepth convolution will no longer be used. If you have any questions after reading all the code, you can mention it again
